name: Simple Workflow
on: [push]

jobs:
  simple-workflow-run:
#    runs-on: self-hosted
    runs-on: self-hosted

    steps:
      - name: Before the repository
        run: |
          ls -l
          pwd
          uname -a

      - name: checkout
        uses: actions/checkout@v4

      - name: After checking the repository  
        run: |
          ls -l
          pwd
