name: Simple Workflow
on: 
  push:
  pull_request:
    types: [opened, assigned, reopened, syncronize]    # Event Types
  issues:
    types: [opened]

jobs:
  simple-workflow-run:
    runs-on: ubuntu-latest
#   runs-on: self-hosted

    steps:
      - name: Before the repository
        run: |
          ls -l
          pwd
          uname -a

      - name: checkout
        uses: actions/checkout@v4

      - name: After checking the repository  
        run: |
          ls -l
          pwd
